# Generated by Django 5.2.3 on 2025-07-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
