# Generated by Django 5.2.3 on 2025-07-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0004_sale_order'),
        ('Shop', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Shop.product'),
        ),
    ]
