# Generated by Django 5.2.3 on 2025-07-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0005_alter_stock_product'),
        ('Shop', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Shop.product'),
        ),
    ]
