# Generated by Django 5.2.3 on 2025-07-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0006_alter_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
