# Generated by Django 5.2.3 on 2025-07-15 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
        ('campusprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=35)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='Shop.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User's Name")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
