# Generated by Django 5.2.3 on 2025-07-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusprofile', '0004_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('vendor', 'vendor')], default='student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('vendor', 'vendor')], default='student'),
            preserve_default=False,
        ),
    ]
