# Generated by Django 5.2.3 on 2025-07-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_store_products_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
