# Generated by Django 5.2.3 on 2025-08-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_store_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='active',
            new_name='currently_active',
        ),
    ]
