# Generated by Django 5.2.3 on 2025-08-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewHub', '0002_remove_review_user_productreview_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
