# Generated by Django 5.2.3 on 2025-08-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewHub', '0003_alter_productreview_unique_together'),
        ('Shop', '0007_alter_product_image'),
        ('campusprofile', '0005_student_role_vendor_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
    ]
